# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  DBName:
    container_name: DBName
    dns_search: .
    image: hyperledger/fabric-couchdb:${FABRIC_BASE_VER}
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "5984:5984"

  PeerName:
    container_name: PeerName
    dns_search: .
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=DBName:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_CHAINCODE_LOGGING_SHIM=DEBUG
      - CORE_PEER_ID=PeerName
      - CORE_PEER_ADDRESS=PeerName:7051
      - CORE_PEER_CHAINCODEADDRESS=PeerName:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=PeerName:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=PeerName:7051
      - CORE_PEER_LOCALMSPID=${PEER_MSPID_NAME}
    volumes:
      - /var/run/:/host/var/run/
      - ${CRYPTO_LOCAL}/peerOrganizations/${PEER_DOMAIN_NAME}/peers/peer0.${PEER_DOMAIN_NAME}/msp:/etc/hyperledger/fabric/msp
      - ${CRYPTO_LOCAL}/peerOrganizations/${PEER_DOMAIN_NAME}/peers/peer0.${PEER_DOMAIN_NAME}/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    depends_on:
      - DBName
