# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  ca0:
    container_name: ca
    image: hyperledger/fabric-ca:${FABRIC_CA_VER}
    network_mode: host
    extra_hosts:
      - 'ca.yzhorg.net:127.0.0.1'
    environment:
      - FABRIC_CA_HOME=${CA_SERVER_REMOTE}
      - FABRIC_CA_SERVER_CA_NAME=ca
      - FABRIC_CA_SERVER_TLS_ENABLED=${TLS_ENABLED}
      - FABRIC_CA_SERVER_TLS_CERTFILE=${CA_SERVER_REMOTE}/ca.yzhorg.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=${CA_SERVER_REMOTE}/CA1_PRIVATE_KEY
    command: sh -c 'fabric-ca-server start --ca.certfile ${CA_SERVER_REMOTE}/ca.yzhorg.net-cert.pem --ca.keyfile ${CA_SERVER_REMOTE}/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ${CA_SERVER_LOCAL}:${CA_SERVER_REMOTE}
    ports:
      - "7054:7054"

  orderer:
    container_name: orderer
    image: hyperledger/fabric-orderer:${FABRIC_IMAGE_VER}
    network_mode: host
    extra_hosts:
#      - "orderer0:${orderer0IP}"
#      - "peer0:${peer0IP}"
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=${ORDERER_SERVER_REMOTE}/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=${ORDERER_SERVER_REMOTE}/msp
      - ORDERER_GENERAL_TLS_ENABLED=${TLS_ENABLED}
#      - ORDERER_GENERAL_BATCHTIMEOUT=1s
      - ORDERER_GENERAL_TLS_PRIVATEKEY=${ORDERER_SERVER_REMOTE}/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=${ORDERER_SERVER_REMOTE}/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[${ORDERER_SERVER_REMOTE}/tls/ca.crt]
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ${ORDERER_SERVER_LOCAL}/artifacts/orderer.block:${ORDERER_SERVER_REMOTE}/genesis.block
      - ${ORDERER_SERVER_LOCAL}/ordererOrganizations/orderer.net/orderers/orderer.orderer.net:${ORDERER_SERVER_REMOTE}
    ports:
      - 7050:7050

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:${FABRIC_IMAGE_VER}
    tty: true
    network_mode: host
    extra_hosts:
#      - "orderer0:${orderer0IP}"
#      - "peer0:${peer0IP}"
    environment:
      - GODEBUG=netdns=go
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer1:7051
      - CORE_PEER_LOCALMSPID=${ORG1_PEER_LOCALMSPID}
      - CORE_PEER_TLS_ENABLED=${TLS_ENABLED}
      - CORE_PEER_TLS_CERT_FILE=${CLI_SERVER_REMOTE_CFG}/peers/peer0.yzhorg.net/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=${CLI_SERVER_REMOTE_CFG}/peers/peer0.yzhorg.net/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=${CLI_SERVER_REMOTE_CFG}/peers/peer0.yzhorg.net/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=${CLI_SERVER_REMOTE_CFG}/users/Admin@yzhorg.net/msp
      - FABRIC_PEERS_LIST=1 2 3
      - FABRIC_ORDERER_LIST=orderer
      - CHANNEL_NAME=${CHAINCODE_CHANNEL}
      - CHAINCODE_NAME=${CHAINCODE_NAME}
      - CHAINCODE_INIT_ARGS=${CHAINCODE_INIT_ARGS}
      - CHAINCODE_INVOKE_ARGS=${CHAINCODE_INVOKE_ARGS}
    working_dir: /cli
    command: /bin/bash -c './scripts/script.sh ${CHAINCODE_CHANNEL} ${CHAINCODE_VERSION} ${CHAINCODE_INSTALL}; sleep $TIMEOUT'
    volumes:
      - /var/run/:/host/var/run/
      - ./scripts:/cli/scripts/
      - ${CLI_SERVER_LOCAL}:${CLI_SERVER_REMOTE}
      - ${LOCAL_GOPATH}/${CHAINCODE_PACKAGE_REMOTE}:/opt/gopath/${CHAINCODE_PACKAGE_REMOTE}
    depends_on:
      - ca0
      - orderer
