# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:
  ca.org1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca/${BYFN_CA1_PRIVATE_KEY}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/tlsca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/${BYFN_CA1_TLS_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config/ca
      - ./crypto-config/peerOrganizations/org1.example.com/tlsca/:/etc/hyperledger/fabric-ca-server-config/tlsca
      - ./crypto-config/peerOrganizations/org1.example.com/ca/${BYFN_CA1_PRIVATE_KEY}:/etc/hyperledger/fabric-ca-server/msp/keystore/${BYFN_CA1_PRIVATE_KEY}
      - ./crypto-config/peerOrganizations/org1.example.com/tlsca/${BYFN_CA1_TLS_PRIVATE_KEY}:/etc/hyperledger/fabric-ca-server/msp/keystore/${BYFN_CA1_TLS_PRIVATE_KEY}
    container_name: ca.org1.example.com
    networks:
      - byfn

  ca.org2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca/${BYFN_CA2_PRIVATE_KEY}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/tlsca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/tlsca/${BYFN_CA2_TLS_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config/ca
      - ./crypto-config/peerOrganizations/org2.example.com/tlsca/:/etc/hyperledger/fabric-ca-server-config/tlsca
      - ./crypto-config/peerOrganizations/org2.example.com/ca/${BYFN_CA2_PRIVATE_KEY}:/etc/hyperledger/fabric-ca-server/msp/keystore/${BYFN_CA2_PRIVATE_KEY}
      - ./crypto-config/peerOrganizations/org2.example.com/tlsca/${BYFN_CA2_TLS_PRIVATE_KEY}:/etc/hyperledger/fabric-ca-server/msp/keystore/${BYFN_CA2_TLS_PRIVATE_KEY}
    container_name: ca.org2.example.com
    networks:
      - byfn
